No more english
Gruppe3/BlazorTipz pull request #47
Opened 2022-10-13 17:59 UTC by sebmid

Rip engelsk da

2022-10-13 18:27 UTC, Eiriksb approved these changes
😢

2022-10-13 21:13 UTC, Trivinyx requested changes
Bare fiks disse så kan vi merge

2022-10-13 21:13 UTC, Trivinyx commented on BlazorTipz/Views/LoginU.razor
> +<p class="d-flex justify-content-center">Fyll inn epost og passord</p>
Dette skal egentilg være AnsattNr. og Passord

2022-10-13 21:13 UTC, Trivinyx commented on BlazorTipz/Views/UserSettings.razor
> +                        <RadzenLabel Text="Gjenta password" />
liten typo

2022-10-18 10:24 UTC, Trivinyx approved these changes

2022-10-18 10:27 UTC, GlennJoakimB approved these changes
Ser greit ut

2022-10-18 10:27 UTC, merged